apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-go-app-agro-main
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/dotrashevskyi/test-app-deployments.git
    targetRevision: HEAD
    path: app-chart-main
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true