apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: go-app=us-central1-docker.pkg.dev/internship-166-375809/internship-repo/test-go-app
    argocd-image-updater.argoproj.io/go-app.update-strategy: latest
    argocd-image-updater.argoproj.io/go-app.allow-tags: regexp:^dev
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/pull-secret: pullsecret:argocd/artifact-registry-secret
  name: my-go-app-agro-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/dotrashevskyi/test-app-deployments.git
    targetRevision: HEAD
    path: app-chart-dev
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true