helm:
  parameters:
  - name: image.name
    value: us-central1-docker.pkg.dev/internship-166-375809/internship-repo/test-go-app
    forcestring: true
  - name: image.tag
    value: dev-06-02-2023-3daac8b
    forcestring: true
